version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: flexipayuser
      POSTGRES_PASSWORD: flexipaypass
      POSTGRES_DB: flexipaydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://flexipayuser:flexipaypass@postgres/flexipaydb

  web:
    build: ./web
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
